//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eorderOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlinea
    {
        public int ID_EMPRESA { get; set; }
        public int ID_LOCAL { get; set; }
        public int ID_LINEA { get; set; }
        public string LINEA { get; set; }
        public Nullable<int> W_ORDEN { get; set; }
    }
}
