//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eorderOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mlocal
    {
        public int ID_EMPRESA { get; set; }
        public int ID_LOCAL { get; set; }
        public Nullable<int> ACTIVA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string RFC { get; set; }
        public string W_CLAVE_EMP { get; set; }
        public string W_NOMBRE { get; set; }
        public string W_DESCRIPCION { get; set; }
        public string W_LOGO { get; set; }
        public string W_IMG_BODY { get; set; }
        public string W_COLOR_BODY { get; set; }
        public string W_COLOR_TEXT { get; set; }
        public string W_LINK_FACEBOOK { get; set; }
        public string W_LINK_TWITTER { get; set; }
        public string W_LINK_GOOGLEPLUS { get; set; }
        public string W_LINK_PINTEREST { get; set; }
        public string W_LINK_INSTAGRAM { get; set; }
        public string W_LINK_OTRO_A { get; set; }
        public string W_LINK_OTRO_B { get; set; }
        public string W_SUBDOMAIN { get; set; }
    }
}
