//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eorderOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mpro
    {
        public int ID_EMPRESA { get; set; }
        public int ID_LOCAL { get; set; }
        public int ID_PRO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public Nullable<int> ID_LINEA { get; set; }
        public Nullable<int> ID_GRUPO { get; set; }
        public Nullable<int> ID_INS { get; set; }
        public Nullable<int> OCULTO { get; set; }
        public Nullable<int> DISPONIBLE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> PRECIO_A { get; set; }
        public Nullable<double> PRECIO_B { get; set; }
        public Nullable<double> PRECIO_C { get; set; }
        public Nullable<int> BLOQUEO { get; set; }
        public Nullable<double> COSTO { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<int> ID_MOD { get; set; }
        public Nullable<int> FSIZE { get; set; }
        public string IVA_T { get; set; }
        public string MPROCLAVE { get; set; }
    }
}
